# Query type enum
uint8 INSERT=0
uint8 DELETE=1
uint8 FETCH=2
uint8 GET=3
uint8 GET_AGGREGATE=4
uint8 DEFINE=5
uint8 UPDATE=6

uint8 query_type
string query
---
bool success
ros_typedb_msgs/ResultTree[] results
