name: documentation

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@0.4.3
        id: action_ros_ci_step
        with:
          package-name: ros_typedb
          target-ros2-distro: humble
          skip-tests: true
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-autopackagesummary sphinx-autodoc-typehints typedb-driver
      - name: Sphinx build
        shell: bash
        run: |
          source ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/install/setup.bash && sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
