name: test
on:
  pull_request:
  push:
    branches:
      - main


jobs:
  test:
    name: build and test ros_typedb pkg
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: install typedb
        run: .github/workflows/install_typedb.sh
      - name: run typedb
        run: typedb server&
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@0.4.3
        with:
          package-name: ros_typedb_msgs ros_typedb
          target-ros2-distro: humble
